apiVersion: apps/v1
kind: Deployment
metadata:
  name: american-predictor-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: american-predictor
  template:
    metadata:
      labels:
        app: american-predictor
    spec:
      containers:
      - name: american-predictor
        image: docker.io/alphabethe/american-predictor:0.2
        ports:
        - containerPort: 5004